def college_list(type, size, location, acceptance)
    type=type.to_sym
    size=size.to_sym
    location=location.to_sym
    acceptance=acceptance.to_sym
    college = {
    :public => {
            :small => {
                    #[[name of college], [description], [image url]]
                    :city => {
                        :very_selective => ["Southern University at New Orleans", "Southern University at New Orleans is a historically African American university located in New Orleans, Louisiana, United States. It is a member of the Southern University System. The University is a member-school of Thurgood Marshall College Fund.Address: 6400 Press Dr, New Orleans, LA 70126. Acceptance rate: 20.7%"],
                        
                        :selective => ["Lehman College", "Lehman College is a senior college of the City University of New York in New York, United States. Founded in 1931 as the Bronx campus of Hunter College, the school became an independent college within CUNY in September 1967.", "New Mexico Institute of Mining and Technology",  "The New Mexico Institute of Mining and Technology is a university located in Socorro, New Mexico. New Mexico Tech offers over 30 bachelor of science degrees in technology, the sciences, engineering. Address: 801 Leroy Pl, Socorro, NM 8780"], 
                        :not_very_selective => ["Vaughn College of Aeronautics and Technology", "Vaughn College of Aeronautics and Technology is a private specialized aviation and engineering college located adjacent to LaGuardia Airport in East Elmhurst, Queens, New York, United States. Address: 8601 23rd Ave, East Elmhurst, NY 11369 Acceptance rate: 74.8% (2014)","Winthrop University", "Winthrop University, often referred to as Winthrop or WU and formerly known as Winthrop College, is a public, coeducational, liberal arts university located in Rock Hill, South Carolina, United States. Address: 701 Oakland Ave, Rock Hill, SC 29733 Acceptance rate: 71.2% (2014)"]
                    },
                    :suburban => {
                        :very_selective => ["College of William and Mary", "The College of William & Mary in Virginia is a public research university located in Williamsburg, Virginia, United States. Address: Sadler Center, 200 Stadium Dr, Williamsburg, VA 23185, Acceptance rate: 34% (2015)", "United States Coast Guard Academy", "The United States Coast Guard Academy is the service academy of the United States Coast Guard, founded in 1876 and located in New London, Connecticut. Address: 31 Mohegan Ave Pkwy, New London, CT 06320, Acceptance rate: 16% (2010)"],
                        :selective => ["Central State University", "Central State University is a historically black university located in Wilberforce, Ohio, United States. It is a member-school of the Thurgood Marshall College Fund. Address: 1400 Brush Row Rd #142, Wilberforce, OH 45384, Acceptance rate: 37.7% (2014)", "Concord University", "Concord University is a comprehensive, public, liberal arts institution located in Athens, West Virginia, United States, founded on February 28, 1872, when the West Virginia Legislature passed an act to build a school in W. VA. Address: 1000 Vermillion Street, Athens, WV 24712, Acceptance rate: 37.8% (2014)"],
                        :not_very_selective => ["College of Charleston", "The College of Charleston is a public sea-grant and space-grant university located in historic downtown Charleston, South Carolina, United States Address: 66 George St, Charleston, SC 29424 Acceptance rate: 77% (2015)", "Sheperd University", "Shepherd University, formerly Shepherd College, is a state-funded university in Shepherdstown, West Virginia, United States. The University currently serves 4,041 students. Address: 301 N King St, Shepherdstown, WV 25443 Acceptance rate: 90% (2015)", "University of North Carolina at Asheville", "The University of North Carolina at Asheville is a co-educational, four year, public liberal arts university. The university is also known as UNC Asheville. Address: 1 University Heights, Asheville, NC 28804 Acceptance rate: 73.1% (2014)", "Ramapo College", "Ramapo College of New Jersey, abbreviated RCNJ, is a public liberal arts and professional studies institution of the New Jersey system of higher education, located in Mahwah, New Jersey, United States, near the Ramapo Mountain. Address: 505 Ramapo Valley Rd, Mahwah, NJ 07430 Acceptance rate: 53% (2015)"]
                    }
                
            },
              :medium => {
                    :city => {
                        :very_selective => ["Georgia Tech", "The Georgia Institute of Technology (commonly referred to as Georgia Tech, Tech, or GT) is a public research university in Atlanta, Georgia, in the United States. It is a part of the University System of Georgia and has satellite campuses around the world. Address: North Ave NW, Atlanta, GA 30332 Acceptance rate: 25% (2016)"],
                        :selective => ["Baruch College", "Baruch College is a public institution that was founded in 1919. It has a total undergraduate enrollment of 15,254, its setting is urban, and the campus size is 3 acres. Address: 55 Lexington Ave, New York, NY 10010 Acceptance rate: 27.6% (2014)", "Hunter College", "Hunter College is one of the constituent colleges of the City University of New York, an American public university. It is located in the Upper East Side of Manhattan, New York City. The college offers studies in more than one hundred undergraduate and postgraduate fields across five schools. Address: 695 Park Ave, New York, NY 10065 Acceptance rate: 34.8% (2014)", "Brooklyn College", "Brooklyn College is a public institution that was founded in 1930. It has a total undergraduate enrollment of 14,207, its setting is urban, and the campus size is 35 acres. It utilizes a semester-based academic calendar. Address: 2900 Bedford Ave, Brooklyn, NY 11210 Acceptance rate: 35.3% (2014)"], 
                        :not_very_selective => ["University of Wisconsin–Milwaukee", "The University of Wisconsin–Milwaukee is a public urban research university located in Milwaukee, Wisconsin, in the United States. It is the largest university in the Milwaukee metropolitan area and a member of the University of Wisconsin System. Address: Milwaukee, WI 53211 Acceptance rate: 89.6% (2014)"]
                    },
                    :suburban => {
                        :very_selective => [],
                        :selective => ["SUNY at Albany", "The State University of New York at Albany, also known as University at Albany, SUNY Albany or UAlbany, is a public research university with campuses in Albany, Guilderland, and Rensselaer, New York, United States. Address: 1400 Washington Ave, Albany, NY 12222 Acceptance rate: 56% (2015)", "University of Virginia", "The University of Virginia, frequently referred to simply as Virginia, is a public research university and the flagship for the Commonwealth of Virginia. Address: Charlottesville, VA 22904,, Acceptance rate: 28.9% (2016)", "Binghamton University", "The State University of New York at Binghamton, commonly referred to as Binghamton University, is a public research university with campuses in Binghamton, Vestal, and Johnson City, New York, United States. Address: 4400 Vestal Parkway East, Binghamton, NY 13902 Acceptance rate: 42% (2015)", "Clemson University", "Clemson University is an American public, coeducational, land-grant and sea-grant research university in Clemson, South Carolina. Clemson is the second largest university in South Carolina. Address: Clemson, SC 29634 Acceptance rate: 51% (2015)"],
                        :not_very_selective => ["Arkansas Tech University", "Arkansas Tech University is a comprehensive regional institution located in Russellville, Arkansas, United States. The university offers programs at both baccalaureate and graduate levels in a range of fields. Address: Doc Bryan, 1605 N Coliseum Dr, Russellville, AR 72801 Acceptance rate: 86.3% (2014)"]
                    }
                
            },
            
                :large => {
                    :city => {
                        :very_selective => ["University of California Berkeley", "The University of California, Berkeley, is a public research university located in Berkeley, California. Founded in 1868, Berkeley is the oldest of the ten research universities affiliated with the University of California system and is ranked as one of the world's leading research universities and the top public university in the United States. Address: Berkeley, CA Acceptance rate: 17.5% (2016)", "UCLA", "The University of California, Los Angeles (UCLA) is a public research university in the Westwood district of Los Angeles, California, United States.It offers 337 undergraduate and graduate degree programs in a wide range of disciplines. Address: 405 Hilgard Avenue, Los Angeles, CA 90095 Acceptance rate: 18% (2016)"],
                        :selective => ["University of Washington Seattle", "Located north of downtown Seattle, the University of Washington is one of the oldest public universities on the West Coast. It is also a cutting-edge research institution and hosts an annual undergraduate research symposium for students to present their work to the community. Address: Seattle, WA 98195 Acceptance rate: 45% (2016)", "University of Texas at Austin", "The University of Texas at Austin is a public research university and the flagship institution of the University of Texas System. Founded in 1881 as The University of Texas, its campus is located in Austin, Texas, approximately 1 mile (1.6 km) from the Texas State Capitol. Address: Austin, TX 78712 Acceptance rate: 39% (2015)", "University of Michigan Ann Arbor", "University of Michigan-Ann Arbor is a public institution that was founded in 1817. It utilizes a trimester-based academic calendar and students can join one of the school’s more than 900 student organizations or 60 Greek chapters. Address: 500 S State St, Ann Arbor, MI 48109 Acceptance rate: 28.6% (2016)", "UCSD", "The University of California, San Diego is a public research university located in the La Jolla neighborhood of San Diego, California, in the United States. Address: 9500 Gilman Dr, La Jolla, CA 92093 Acceptance rate: 35.9% (2016)"] ,
                        :not_very_selective => ["California State University, Los Angeles", "California State University, Los Angeles is a public comprehensive university in the heart of Los Angeles, one of the 23 universities in the California State University system. Address: 5151 State University Dr, Los Angeles, CA 90032 Acceptance rate: 68% (2015)"]
                    },
                    :suburban => {
                        :very_selective => ["UC Davis", "The University of California, Davis, is a public research university and land-grant university as well as one of the 10 campuses of the University of California system. Address: 1 Shields Ave, Davis, CA 95616 Acceptance rate: 42.3% (2016)"],
                        :selective => ["University of South Carolina", "The University of South Carolina is a public, co-educational research university in Columbia, South Carolina, United States, with seven satellite campuses. The University is categorized by the Carnegie Foundation for the Advancement of Teaching as having highest research activity. Address: Columbia, SC 29208 Acceptance rate: 65% (2015)", "University at Buffalo", "It is commonly referred to as the University at Buffalo (UB) or SUNY Buffalo, and was formerly known as the University of Buffalo. The university was founded in 1846 as a private medical university, but in 1962 merged with the State University of New York (SUNY) system. Address: Buffalo, NY 14260 Acceptance rate: 57.8% (2014)", "Rutgers University", "Rutgers University is an American public research university and the largest institution for higher education in New Jersey. It is the eighth-oldest college in the United States and one of the nine colonial colleges chartered before the American Revolution. Address: 7 College Ave, New Brunswick, NJ 08901 Acceptance rate: 58% (2015)"], 
                        :not_very_selective => ["Auburn University", "Auburn University (AU or Auburn) is a public research university in Auburn, Alabama, United States. Auburn University is one of the state's two public flagship universities. Address: Auburn, AL 36849 Acceptance rate: 77.7% (2016)"]
                    }
                
            }  
        },
            
            

        :private => {
            :small => {
                    :city => {
                        :very_selective => ["Vanderbilt University", "Vanderbilt University is a private research university founded in 1873 and located in Nashville, Tennessee. Address: 2201 West End Ave, Nashville, TN 37235 Acceptance rate: 10.7% (2016)", "Tufts University", "Tufts University is organized into ten schools, including two undergraduate degree programs and eight graduate divisions, on four campuses in the Boston metropolitan area and the French Alps. The university emphasizes active citizenship and public service in all of its disciplines,and is known for its internationalism and study abroad programs. Address: 419 Boston Ave, Medford, MA 02155‎ Acceptance rate: 14% (2016)", "Cooper Union", "The Cooper Union for the Advancement of Science and Art is a privately funded college located in Cooper Square in the East Village neighborhood of Manhattan, New York City. Address: 30 Cooper Sq, New York, NY 10003 Acceptance rate: 15.1% (2014)", "Massachusetts Institue of Technology", "The Massachusetts Institute of Technology (MIT) is a private research university in Cambridge, Massachusetts. It is often ranked as one of the world's most prestigious universities. MIT adopted a European polytechnic university model and stressed laboratory instruction in applied science and engineering. Address: 77 Massachusetts Ave, Cambridge, MA 02139 Acceptance rate: 7.9% (2016)"], 
                        :selective => ["Colgate University", "Colgate University is a private liberal arts college located on 575 acres in Hamilton Village, Hamilton Township, Madison County, New York, United States. Colgate has 55 undergraduate concentrations that culminate in a Bachelor of Arts degree. Address: 13 Oak Dr, Hamilton, NY 13346 Acceptance rate: 28.7% (2016)"] ,
                        :not_very_selective => ["Carlow University", "Carlow University is a private, co-educational, Catholic university located in the heart of Pittsburgh’s “Tech, Ed, and Med” district. Address: 3333 Fifth Ave, Pittsburgh, PA 15213 Acceptance rate: 90.7% (2014)"]
                    },
                    :suburban => {
                        :very_selective => ["California Institute of Technology", "The California Institute of Technology (abbreviated Caltech)[6] is a private doctorate-granting university located in Pasadena, California, United States. The university is one among a small group of institutes of technology in the United States which is primarily devoted to the instruction of technical arts and applied sciences. Address: 1200 E California Blvd, Pasadena, CA 91125  Acceptance rate: 8% (2016)", "Pomona College", "Pomona College is a private, nonsectarian, coeducational, liberal arts college in Claremont, California, United States. Established in 1887, it is the founding member of the Claremont Colleges consortium. Address: Sumner Hall, 333 N College Way, Claremont, CA 91711  Acceptance rate: 9.1% (2016)", "Amherst College", "Amherst College is a private liberal arts college located in Amherst, Massachusetts, United States. It was founded in 1821 as an attempt to relocate Williams College by its president, Zephaniah Swift Moore. Address: Amherst, MA 01002  Acceptance rate: 14% (2016)", "Bowdoin College", "Bowdoin College is a private liberal arts college located in Brunswick, Maine. At the time Bowdoin was chartered in 1794, Maine was still a part of the Commonwealth of Massachusetts. Address: 255 Maine St, Brunswick, ME 04011  Acceptance rate: 14.3% (2016)"],
                        :selective => ["Smith College", "Smith College is a private, independent women's liberal arts college with coed graduate and certificate programs, located in Northampton, Massachusetts, United States. It is the largest member of the Seven Sisters. Address: Northampton, MA 01063  Acceptance rate: 36% (2015)", "Albright College", "Albright College is a private, co-educational, liberal arts college. It was founded in 1856 and is located in Reading, Pennsylvania, United States. Albright College has been named one of the best Northeastern schools for 13 consecutive years by The Princeton Review and has also been named one of the most ethnically and economically diverse schools in the country by U.S News and World Report. Address: 1621 N 13th St, Reading, PA 19604 Acceptance rate: 50.1% (2014)"],
                        :not_very_selective => ["Hofstra University", "Hofstra University is a private, non-profit, nonsectarian university in the United States. Its main campus is on Long Island in the village of Hempstead, New York, approximately 7 miles east of New York City. Address: 1000 Fulton Ave, Hempstead, NY 11549  Acceptance rate: 61.6% (2014)"]
                    }
                
                },
                    :medium => {
                
                    :city => {
                        :very_selective => ["Harvard", "Harvard University is a private Ivy League research university in Cambridge, Massachusetts, established in 1636, whose history, influence, and wealth have made it one of the world's most prestigious universities. Address: Cambridge, MA 02138 Acceptance rate: 5.4% (2016)", "University of Pennsylvania","The University of Pennsylvania is a private Ivy League research university located in Philadelphia, Pennsylvania, United States. Incorporated as The Trustees of the University of Pennsylvania, Penn is one of 14 founding members of the Association of American Universities and one of the nine colonial colleges chartered before the American Revolution. Address: Philadelphia, PA 19104 Acceptance rate: 9.4% (2016)" ,"University of Chicago", "The University of Chicago is a private research university in Chicago, Illinois established in 1890, which holds top-ten positions in numerous national and international rankings. Address: 5801 S Ellis Ave, Chicago, IL 60637 Acceptance rate: 7.9% (2016)","Stanford", "Stanford University is a private research university in Stanford, California, adjacent to Palo Alto and between San Jose and San Francisco. Stanford's undergraduate program is the most selective in America. Address: 450 Serra Mall, Stanford, CA 94305 Acceptance rate: 4.8% (2016)", "University of Southern California", "The University of Southern California is a private research university located in Los Angeles, California. Founded in 1880, it is the oldest private research university in California. Address: Los Angeles, CA 90007 Acceptance rate: 16.5% (2016)"], 
                        :selective => ["Tulane University", "Tulane University is a private, nonsectarian research university in New Orleans, Louisiana, United States. It is considered the top university and the most selective institution of higher education in the state of Louisiana. Address: 6823 St Charles Ave, New Orleans, LA 70118 Acceptance rate: 30% (2015)", "Keiser University", "Keiser University is a private non-profit university based in Florida. Keiser provides educational programs at the undergraduate and graduate levels in traditional and online delivery formats. Address: 1500 NW 49th St, Fort Lauderdale, FL 33309 Acceptance rate: 48.7% (2015)"],
                        :not_very_selective => ["Pace University", "Pace University is a private institution that was founded in 1906. It has a campus in Manhattan, New York City, and two campuses in Westchester County, New York, in Pleasantville and White Plains. Address: 1 Pace Plaza, New York, NY 10038 Acceptance rate: 66% (2015)"]
                    },
                    :suburban => {
                        :very_selective => ["Cornell University", "Cornell University is a private and statutory Ivy League research university located in Ithaca, New York. Founded in 1865 by Ezra Cornell and Andrew Dickson White, the university was intended to teach and make contributions in all fields of knowledge—from the classics to the sciences, and from the theoretical to the applied. Address: Ithaca, NY, 14850 Acceptance rate: 14.1% (2016)"], 
                        :selective => ["American University", "The American University is a private research university in Washington, D.C., United States, located in the Tenleytown neighborhood in the northwest portion of the district. Address: 4400 Massachusetts Ave NW, Washington, DC 20016 Acceptance rate: 25.7% (2016)"],  
                        :not_very_selective => ["Adelphi University", "Adelphi University is a private, nonsectarian university located in Garden City, in Nassau County, New York, United States. Adelphi also has centers in Manhattan, Hudson Valley, and Suffolk County. Address: 1 South Ave, Garden City, NY 11530 Acceptance rate: 72% (2015)"]
                    }
                
            },
                :large => {
                    :city => {
                        :very_selective => ["Columbia University", "Columbia University, established in 1754, is a private Ivy League research university in Upper Manhattan, New York City, often cited as one of the world's most prestigious universities. Address: 116th St & Broadway, New York, NY 10027 Acceptance rate: 6% (2016)"],
                        :selective => ["Fordham University", "Fordham University is a private, independent research university in New York City, founded by the Catholic Diocese of New York in 1841. Address: Bronx, NY 10458 Acceptance rate: 44% (2016)", "New York University", "New York University is a private nonprofit research university based in New York City. Founded in 1831, NYU's main campus is centered in Manhattan, located with its core in Greenwich Village, and campuses based throughout New York City. Address: New York, NY 10003 Acceptance rate: 33% (2015)","Nova Southeastern University", "Nova Southeastern University is a private nonprofit university, with a main campus located on 300 acres in Davie, in the US state of Florida. Address: 3301 College Ave, Fort Lauderdale, FL 33314 Acceptance rate: 48.8% (2014)"] ,
                        :not_very_selective => ["DePaul University", "DePaul University is a private university in Chicago, Illinois. Founded by the Vincentians in 1898, the university takes its name from the 17th-century French priest Saint Vincent de Paul. Address: 1 E Jackson Blvd, Chicago, IL 60604 Acceptance rate: 72% (2015)", "Drexel University", "Drexel University is a private research university with three campuses in Philadelphia. It was founded in 1891 by Anthony J. Drexel, a noted financier and philanthropist. Address: 3141 Chestnut St, Philadelphia, PA 19104 Acceptance rate: 75% (2015)"]
                    },
                    :suburban => {
                        :very_selective => [], 
                        :selective => ["Brigham Young University", "Brigham Young University is a private research university in Provo, Utah, United States. It is owned and operated by The Church of Jesus Christ of Latter-day Saints, and excluding online students, is the largest religious university and the third largest private university in the United States, with 29,672 on-campus students. Address: Provo, UT 84602 Acceptance rate: 53.5% (2016)"], 
                        :not_very_selective => ["Western Governors University", "Western Governors University is a private, nonprofit, online American university based in Salt Lake City, Utah. Address: 4001 S 700 E #700, Salt Lake City, UT 84107 Acceptance rate: 98% (2016)"]
                    }
                
            }  
        }
            
            
    
    }     
            
    

return college[type][size][location][acceptance]

end 


# puts college_list(:private, :medium, :city, :very_selective)